name: 💡 功能请求
description: 请求一个新功能或功能增强
title: "[Request]: "
labels: ["feature"]
assignees: [abgox]
body:
  - type: textarea
    id: description
    attributes:
      label: 描述这个功能请求
      description: |
        请详细描述您的功能要求或增强。
        它解决了 InputTip 中的哪些不足?
        哪些用例支持您的请求?
    validations:
      required: true
  - type: dropdown
    id: windows-version
    attributes:
      label: 你正在使用什么 Windows 系统版本?
      description: 如果是 Windows 10 以前的系统，请选择 `其他`, 并在最后的补充信息中说明具体系统版本。
      options:
        - Windows 11
        - Windows 10
        - 其他
      multiple: true
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
